# This property is used to disable default web server
# spring.main.web-application-type=none

#spring:
#  profiles:
#    active: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demospringboot
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

#  Redis configuration
  redis:
    host: localhost
    port: 6379

#  Swagger Configuration
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#logging:
#  level:
#    root: DEBUG
