# This property is used to disable default web server
# spring.main.web-application-type=none

#spring:
#  profiles:
#    active: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demospringboot
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true